DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS contact;

CREATE TABLE contact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  surname TEXT NOT NULL,
  age INTEGER NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  contact_id INTEGER NOT NULL,
  FOREIGN KEY (contact_id) REFERENCES contact (id)
);

